name: TypeChecking
on:
  push:
  pull_request:
    paths:
      - '*.py'
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v27
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: nix-shell --command "mypy audiobookdl"
